version: "3"
services:
  
  quoter-app:
  
    build: ${QUOTER_SERVICE_PATH}/Docker/app/.
    container_name: ${QUOTER_SERVICE_NAME}
    command: ["npm", "run", "dev"]
  
    env_file:
      - ${QUOTER_SERVICE_PATH}/Docker/app/.env
      - .env
    
    environment:
      - SEQUELIZE_HOST=${QUOTER_MYSQL_NAME}
      - SEQUELIZE_DATABASE=${QUOTER_MYSQL_DATABASE}      

    volumes:
      - ${QUOTER_SERVICE_PATH}/src:/app/src      
      
    ports:
      - ${QUOTER_APP_PORT}:8080
    
    depends_on:
      - quoter-mysql      
  
  quoter-mysql:
    
    platform: linux/x86_64
    build: ${QUOTER_SERVICE_PATH}/Docker/database/.
    restart: always
    container_name: ${QUOTER_MYSQL_NAME}
  
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=${QUOTER_MYSQL_DATABASE}

    ports:
      - ${QUOTER_MYSQL_PORT}:3306
  
    command: 
      - --default-authentication-plugin=mysql_native_password   